### ISSUE TITLE
When Building from source, plugin does not Compile Correctly - UE 5.4

### ISSUE THREAD

**Issue by kapsy122021** [NinevaStudios/mqtt-utilities-unreal#48]
Hello, I am trying to compile this plugin for use in UE 5.4 and I keep getting this error when building through windows powershell:

_[9/19] Compile [x64] MqttUtilitiesBPL.cpp (0:05.26 at +0:00)
C:\Users\20036153\Documents\GitHub\UnrealEngine\Engine\Source\Runtime\CoreUObject\Public\UObject\ScriptInterface.h(27) : error C4702: unreachable code
   inlined at C:\Users\20036153\Documents\GitHub\UnrealEngine\Engine\Source\Runtime\CoreUObject\Public\UObject\ScriptInterface.h(151) <call to FScriptInterface::FScriptInterface>
   inlined at C:\Users\20036153\Documents\GitHub\UnrealEngine\Downloads\HostProject\Plugins\MqttUtilities\Source\MqttUtilities\Private\MqttUtilitiesBPL.cpp(40) <call to TScriptInterface<IMqttClientInterface>::TScriptInterface<IMqttClientInterface>>
   while compiling UMqttUtilitiesBPL::CreateMqttClient

Error executing C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (tool returned code: 2)_

For what it's worth, this is my first time having to build a plugin externally since it did not work after following the steps provided(Though it did work with UE 5.2, 5.0 and 4.27 for me). Any suggestions on how to resolve this?

![MQTTissue](https://github.com/user-attachments/assets/f5353e8b-724e-4800-a98d-d6ede7ec73a5)

**Comment by kumaran-a11** [comment]
I have the same issue

**Comment by lteleha** [comment]
Found a temp solution here and was able to build the plugin:
https://forums.unrealengine.com/t/plugin-build-fails-only-on-ue5-4/1853592/12

screenshot of solution
![image](https://github.com/user-attachments/assets/74bef31d-4a19-402e-97f0-80d858c9cfc3)

**Comment by ddelanne** [comment]
Same issue on 5.5 via command prompt. Even with the hotfix from the link.
![image](https://github.com/user-attachments/assets/cb9477ca-5882-4eec-b8b5-f8de2d519cf4)

**Comment by Abigon** [comment]
![image](https://github.com/user-attachments/assets/98539f12-ed52-4526-973b-178608641f80)
try this fix

**Comment by ennorehling** [comment]
I submitted PR #51 for this earlier today, and it was just merged (thanks!)
